// ---------------------------------------------------------------------------
// File Serve API — Serve generated files (PDF, DOCX, XLSX, etc.)
//
// Strategy:
// 1. Check in-memory cache first (files generated during this server instance's lifetime)
// 2. Fall back to /tmp filesystem (for local dev and GitHub Actions executor)
// ---------------------------------------------------------------------------

import { NextRequest, NextResponse } from "next/server";
import { readFile, stat } from "fs/promises";
import { join, resolve, extname } from "path";
import { tmpdir } from "os";
import { getCachedFile } from "@/lib/file-cache";

// Map of content types for generated files
const CONTENT_TYPES: Record<string, string> = {
  ".pdf": "application/pdf",
  ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ".txt": "text/plain",
  ".csv": "text/csv",
  ".json": "application/json",
  ".md": "text/markdown",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
};

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ fileId: string }> },
) {
  try {
    const { fileId } = await params;

    // Security: only allow alphanumeric, dash, underscore, dot
    if (!/^[a-zA-Z0-9._-]+$/.test(fileId)) {
      return NextResponse.json({ error: "Invalid file ID" }, { status: 400 });
    }

    const safeFileId = fileId.startsWith("klaw-") ? fileId : `klaw-${fileId}`;
    const ext = extname(fileId).toLowerCase();
    const contentType = CONTENT_TYPES[ext] || "application/octet-stream";

    // Strategy 1: Check file cache (in-memory fast-path + Supabase Storage persistent)
    const cached = await getCachedFile(safeFileId) || await getCachedFile(fileId);
    if (cached) {
      return new NextResponse(new Uint8Array(cached.buffer), {
        headers: {
          "Content-Type": cached.mimeType || contentType,
          "Content-Length": String(cached.buffer.length),
          "Content-Disposition": `inline; filename="${cached.filename || fileId}"`,
          "Cache-Control": "private, max-age=3600",
        },
      });
    }

    // Strategy 2: Fall back to /tmp filesystem (local dev / GitHub Actions)
    const filePath = join(tmpdir(), safeFileId);

    // Check file exists and is in /tmp
    const fileStat = await stat(filePath).catch(() => null);
    if (!fileStat || !fileStat.isFile()) {
      return NextResponse.json({ 
        error: "File not found. Files generated by agents expire after 10 minutes. Please ask the agent to regenerate the document.",
      }, { status: 404 });
    }

    // Verify the resolved path is still in /tmp (prevent path traversal)
    const resolved = resolve(filePath);
    const tmpResolved = resolve(tmpdir());
    if (!resolved.startsWith(tmpResolved)) {
      return NextResponse.json({ error: "Invalid file path" }, { status: 400 });
    }

    // Read file
    const buffer = await readFile(filePath);

    return new NextResponse(buffer, {
      headers: {
        "Content-Type": contentType,
        "Content-Length": String(buffer.length),
        "Content-Disposition": `inline; filename="${fileId}"`,
        "Cache-Control": "private, max-age=3600",
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to serve file";
    console.error("[Files] Error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
